--
-- PostgreSQL database dump
--

-- Dumped from database version 17.2 (Debian 17.2-1.pgdg120+1)
-- Dumped by pg_dump version 17.2 (Debian 17.2-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: movies; Type: TABLE; Schema: public; Owner: databaseadmin
--

CREATE TABLE public.movies (
    id bigint NOT NULL,
    description character varying(1000) NOT NULL,
    director character varying(100) NOT NULL,
    image_url character varying(255) NOT NULL,
    name character varying(100) NOT NULL,
    rating double precision NOT NULL,
    release_date date NOT NULL
);


ALTER TABLE public.movies OWNER TO databaseadmin;

--
-- Name: movies_id_seq; Type: SEQUENCE; Schema: public; Owner: databaseadmin
--

ALTER TABLE public.movies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: revoked_tokens; Type: TABLE; Schema: public; Owner: databaseadmin
--

CREATE TABLE public.revoked_tokens (
    id bigint NOT NULL,
    token character varying(2048) NOT NULL
);


ALTER TABLE public.revoked_tokens OWNER TO databaseadmin;

--
-- Name: revoked_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: databaseadmin
--

ALTER TABLE public.revoked_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.revoked_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: databaseadmin
--

CREATE TABLE public.users (
    is_admin boolean NOT NULL,
    id bigint NOT NULL,
    phone_number character varying(9) NOT NULL,
    username character varying(30) NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL
);


ALTER TABLE public.users OWNER TO databaseadmin;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: databaseadmin
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: movies; Type: TABLE DATA; Schema: public; Owner: databaseadmin
--

COPY public.movies (id, description, director, image_url, name, rating, release_date) FROM stdin;
4	Thriller science fiction o inwazji na sny.	Christopher Nolan	https://m.media-amazon.com/images/S/pv-target-images/e826ebbcc692b4d19059d24125cf23699067ab621c979612fd0ca11ab42a65cb._SX1080_FMjpg_.jpg	Incepcja1	8.8	2010-07-16
6	Thriller science fiction o inwazji na sny.	Christopher Nolan	https://m.media-amazon.com/images/S/pv-target-images/e826ebbcc692b4d19059d24125cf23699067ab621c979612fd0ca11ab42a65cb._SX1080_FMjpg_.jpg	Incepcja - super nowa czesc	8.8	2010-07-16
2	Rozszerzona wersja thrillera science fiction o inwazji na sny. Rozszerzona wersja thrillera science fiction o inwazji na sny. 	Christopher Nolan	https://m.media-amazon.com/images/S/pv-target-images/e826ebbcc692b4d19059d24125cf23699067ab621c979612fd0ca11ab42a65cb._SX1080_FMjpg_.jpg	Incepcja - Rozszerzona Edycja	9	2010-07-16
7	Film 2	Jakub Wojtas	https://thumbs.dreamstime.com/b/film-%C5%82upkowa-i-ekranowa-rolka-na-drewnie-36502412.jpg	Nowy	5.4	1999-01-26
\.


--
-- Data for Name: revoked_tokens; Type: TABLE DATA; Schema: public; Owner: databaseadmin
--

COPY public.revoked_tokens (id, token) FROM stdin;
1	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwiaWF0IjoxNzM3MzA0MzMyLCJleHAiOjE3MzczNDAzMzJ9.Gs3QkQZvIwb-WYvD-aflff26b4KgCJZ6xDw4qdBYBMA
2	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwiaWF0IjoxNzM3MzA0ODQwLCJleHAiOjE3MzczNDA4NDB9.Kar8B5pneCbi1A7dqtNL20KV7YteJNbSf5OxSgOK0Ok
3	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczNzM5ODI2NSwiZXhwIjoxNzM3NDM0MjY1fQ.SmkJMO1VBPE-3ihJy0UkImk-md7NCqYkYHNV_GgCugM
4	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczNzM5ODc2MSwiZXhwIjoxNzM3NDM0NzYxfQ.yx-yzLt1GzpZn1wsoGJkdOiK1k4fqJvriGqUh5pFFwQ
5	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwiaWF0IjoxNzM3Mzk4ODE0LCJleHAiOjE3Mzc0MzQ4MTR9.qt54N-keCNOyEw-9uBJDYu8PpeuHYsHw8wjHc-DF_RE
6	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczNzM5OTAyMSwiZXhwIjoxNzM3NDM1MDIxfQ.0ptdZMbz3biZp_BL_bKOespqVqDEDNFPKiKCkaxdr_U
7	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczNzQwMDE3NCwiZXhwIjoxNzM3NDM2MTc0fQ.n_7ltEb_j0JKWb729QK0zW1u2DlFIITtS9w5xhyVSO4
8	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczNzQwMDE5NywiZXhwIjoxNzM3NDM2MTk3fQ.VQnZFcdGW8fQeZBVhZ3-WD10CBBleO0wyTf9eMWNgWM
9	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczNzU0MTY5NSwiZXhwIjoxNzM3NTc3Njk1fQ.-vQ1JzoOHxC39u6ejbjKGN8y6MnQf5JlXB3c6yQ58-Y
10	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczNzU0MTczNSwiZXhwIjoxNzM3NTc3NzM1fQ.rKe4mHpA9fgU16lIaGiiR8R5lXsMkf5r_GmYliNJXbM
11	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwiaWF0IjoxNzM3NTQxNzUzLCJleHAiOjE3Mzc1Nzc3NTN9.76gRzRKD2Mg-HuolrsYnggiCqdy7ePN0xxbJXVthmIk
12	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczNzU0MTc2MCwiZXhwIjoxNzM3NTc3NzYwfQ.JNmclAkrlnbUyEYBakGgNv3JT5cKrXi5ggs2XjS8iqk
13	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczNzU0MzA3NCwiZXhwIjoxNzM3NTc5MDc0fQ.4f6EBXCNogeyJ2SnCxasV_908ntXv3MtvLxwywwOhRQ
14	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwiaWF0IjoxNzM3NTQzMDgxLCJleHAiOjE3Mzc1NzkwODF9.rrdbDIBbppDOa_ROb0B64Q2nOa2mhGbVeqNe46KyzUQ
15	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczNzU0MzEwNywiZXhwIjoxNzM3NTc5MTA3fQ.9fxYghQAcbdYV9F7YqspLLzS7I2YleqxIxPLaUcCWG8
16	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczNzU0MzQ0NSwiZXhwIjoxNzM3NTc5NDQ1fQ.l7Q6qA__nbXS8SV3z78lz94pRHgaWRSVXa71XsoCSTI
17	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczNzU0MzY1NSwiZXhwIjoxNzM3NTc5NjU1fQ.iiLLrPPzLrwDjEBunRfHA0AMEHqyGHsFybkexIxOZEo
18	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczNzU0Mzg5MSwiZXhwIjoxNzM3NTc5ODkxfQ.1BfsBl7_RhwknyVVmzwRcK7A7qLyyT7hUxTP-BAX-nM
19	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczNzU0NDI1NCwiZXhwIjoxNzM3NTgwMjU0fQ.-2ateH_i8ld46Kp7zGeeMPEA6oZI9CT-OyZiBXU-bUg
20	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwiaWF0IjoxNzM3NTQ0NTIzLCJleHAiOjE3Mzc1ODA1MjN9.x8tTpPutSBMe2be4yyXnYzwYU7yC17sYUQLpqqLDYwc
21	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczNzU0NDY2MSwiZXhwIjoxNzM3NTgwNjYxfQ.G8_BdUrNCsNR0A7gftQsN0a0vFdHAfWOu3jeBLGkReY
22	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczNzU0NDkyMywiZXhwIjoxNzM3NTgwOTIzfQ.XqPv4HibxbJfRKcb0yUC67yEvGhk-MJc9IcnA5Jl0UQ
23	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczNzU0NTA1MSwiZXhwIjoxNzM3NTgxMDUxfQ.RWNCtDAe-e-0kcXB8_VWFJk8Y-yJYTfb2hIf2TtWrwI
24	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczNzU0NTMxOSwiZXhwIjoxNzM3NTgxMzE5fQ.vn_5nGNISp8PfxbGJg_Fo_XZ2EMmlbukcqR0c1dEmFU
25	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwiaWF0IjoxNzM3NTQ1Mzg3LCJleHAiOjE3Mzc1ODEzODd9.__jCpf9eyFOuhALA6spjfP0WwAmlxRZEcWbIVqeqacc
26	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczNzU0NTQwNiwiZXhwIjoxNzM3NTgxNDA2fQ.QVNOqTn1pjygTb8rOLn3UMozJXdJu5aUgWWC-SoVc4I
27	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczNzU0NTg2MCwiZXhwIjoxNzM3NTgxODYwfQ.R8FVkJrkNnQi16TtxlEXCOfbXdW5j3i838O-1606bzs
28	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwiaWF0IjoxNzM3NTQ2MDMwLCJleHAiOjE3Mzc1ODIwMzB9.w9J-mkiSeMbH7Z91Y-lPXZw9bJ15VuKodlziFVrIkjA
29	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczNzU0NjMzMiwiZXhwIjoxNzM3NTgyMzMyfQ.i3hWim7vGLOGtXMcK_ZlUf4Ux0akv-DZdz1wghxdjug
30	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczNzU0NzY3OCwiZXhwIjoxNzM3NTgzNjc4fQ.wYX-mxk7t4FBQXZQAdhhNJCmNlKBHegsuILe_6MeqD4
31	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczNzU0Nzc1MywiZXhwIjoxNzM3NTgzNzUzfQ.udwjAeoD8T1QtWaZO0XSh22ik1l5ICq5RjYtW589ZX8
32	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczNzU0ODU0NCwiZXhwIjoxNzM3NTg0NTQ0fQ.aAhuL060ylLYk3lAWfZY92M7qsbgk5h8tEA9WhHCccQ
33	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwiaWF0IjoxNzM3NTQ5MDI4LCJleHAiOjE3Mzc1ODUwMjh9.CzP9mBiotUInNN9bhNnvdGfrF7AoIsyKhMnjoUW5ZkE
34	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczNzU0OTIwMywiZXhwIjoxNzM3NTg1MjAzfQ.V9gmOsu3kCxL3mRzzvfID2YSp5aHM5S-6eeWelzwdxQ
35	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczNzU1MTM3MiwiZXhwIjoxNzM3NTg3MzcyfQ.3ulBqzZqdtR1_G3RCf_KFEmZsFq9MCrj9kbskPu5TiA
36	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczNzU1MTY0NiwiZXhwIjoxNzM3NTg3NjQ2fQ.9uwZ-ESVaKstSWpzQ4sXP70CGBechtuFpX6twRxjymw
37	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwiaWF0IjoxNzM3NTU0MzAxLCJleHAiOjE3Mzc1OTAzMDF9.3vEVszfe1VvrTjlb9a5_FR8xWKFiGuY8dFwtoF12PPU
38	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczNzU4MDg0MSwiZXhwIjoxNzM3NjE2ODQxfQ.cz0_jzCLlisWwd3UBpC_IM57san-C-BZf4-OGDvhuKw
39	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwiaWF0IjoxNzM3NTgwODUwLCJleHAiOjE3Mzc2MTY4NTB9.E4MWfXDfkOlWEAbkL0cxM3dajtKyvSETIuop2T1C7qA
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: databaseadmin
--

COPY public.users (is_admin, id, phone_number, username, first_name, last_name, email, password) FROM stdin;
f	2	111222335	user	User	Userowski2	user@user.com	$2a$10$u02t7jZvb2A3kwaJhobs7uXKmIx5AYWFUID.h4t44HqA.rhSXHwni
t	1	000111222	admin	Admin	Adminowski	admin@admin.com	$2a$10$u02t7jZvb2A3kwaJhobs7uXKmIx5AYWFUID.h4t44HqA.rhSXHwni
f	5	987654321	jacek_kowalski	Jacek	Kowalski	jacek@example.com	$2a$10$fBYa1Yd.TkhdMQURQPObLusEOz.nEABVGG3xOKMa6p4kJWBRYF2ba
t	15	111222333	kamilek	Kamil	Kamilowski	kamil@kamil.com	$2a$10$2PZqF1IS/zzt3bgNxtDdjODd3ExA4xFcXI.ZpWQVZpXc/6fXKrNx6
\.


--
-- Name: movies_id_seq; Type: SEQUENCE SET; Schema: public; Owner: databaseadmin
--

SELECT pg_catalog.setval('public.movies_id_seq', 8, true);


--
-- Name: revoked_tokens_id_seq; Type: SEQUENCE SET; Schema: public; Owner: databaseadmin
--

SELECT pg_catalog.setval('public.revoked_tokens_id_seq', 39, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: databaseadmin
--

SELECT pg_catalog.setval('public.users_id_seq', 17, true);


--
-- Name: movies movies_pkey; Type: CONSTRAINT; Schema: public; Owner: databaseadmin
--

ALTER TABLE ONLY public.movies
    ADD CONSTRAINT movies_pkey PRIMARY KEY (id);


--
-- Name: revoked_tokens revoked_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: databaseadmin
--

ALTER TABLE ONLY public.revoked_tokens
    ADD CONSTRAINT revoked_tokens_pkey PRIMARY KEY (id);


--
-- Name: revoked_tokens revoked_tokens_token_key; Type: CONSTRAINT; Schema: public; Owner: databaseadmin
--

ALTER TABLE ONLY public.revoked_tokens
    ADD CONSTRAINT revoked_tokens_token_key UNIQUE (token);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: databaseadmin
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: databaseadmin
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: databaseadmin
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- PostgreSQL database dump complete
--

